### ISSUE TITLE
Device unavailable after ticking on battery in settings

### ISSUE THREAD

**Issue by Mimomaj** [reyntjensw/Homey-FusionSolar#18]
Hi, could you please take a look at my problem?
After I tick a battery option in the settings of the app, when the data is updated (5 mins or restart of the app) the device becomes unavailable: 
![image](https://user-images.githubusercontent.com/45653655/201908947-080c7798-603c-48db-98fc-7e2644792ad5.png)

My setup:
inverter - SUN2000-5KTL-M1
battery - LUNA2000 5kWh

**Comment by Mimomaj** [comment]
diagnostic report: e85a666b-9998-4f22-91e7-d778f0038e58

**Comment by reyntjensw** [comment]
Hi @Mimomaj 

Can you share your api key via email please? wouter@chismoor.net

I need to investigate

**Comment by reyntjensw** [comment]
@Mimomaj can you please install this version and try again? https://homey.app/a/com.huawei.solar/

**Comment by Mimomaj** [comment]
@reyntjensw sure, I'll test it tomorrow

**Comment by ludwich** [comment]
@Mimomaj is this working? Close this if it is.

**Comment by Mimomaj** [comment]
@ludwich sorry I forgot to post update.
Unfortunately no, same behavior as previous version.

**Comment by reyntjensw** [comment]
@Mimomaj are you already using the latest version? It was released this morning

**Comment by Mimomaj** [comment]
Yes latest version 1.0.39
![B4460F65-E8E4-4E97-9BCB-E55EB1112BC1](https://user-images.githubusercontent.com/45653655/210228376-6b5125f8-7b42-4618-a44b-7e15b42be53e.png)

**Comment by reyntjensw** [comment]
> Hi @Mimomaj
> 
> Can you share your api key via email please? [wouter@chismoor.net](mailto:wouter@chismoor.net)
> 
> I need to investigate

@Mimomaj can you share this data please?

**Comment by ludwich** [comment]
And error logs would show more info now.

**Comment by reyntjensw** [comment]
The system sees the battery but is unable to query it.
It keeps return a 305 error, for this I think you better contact Huawei support, unless @ludwich has another suggestion?

`[log] 2023-01-08 16:05:33 [ManagerDrivers] [Driver:luna] [Device:a4b280a6-2c12-45b5-890e-149a6216f43f] devListpowerMeterId {
  devName: 'Battery-1',
  devTypeId: 39,
  esnCode: null,
  id: 1000000035658220,
  invType: null,
  latitude: 48.224056,
  longitude: 17.242726,
  optimizerNumber: null,
  softwareVersion: null,
  stationCode: 'NE=xxxxx'
}
apiData getDevRealKpi values:  { failCode: 305, immediately: true, message: 'USER_MUST_RELOGIN' }
[log] 2023-01-08 16:05:33 [ManagerDrivers] [Driver:luna] [Device:a4b280a6-2c12-45b5-890e-149a6216f43f] devRealKpiBattery null
apiData getDevRealKpi values:  { failCode: 305, immediately: true, message: 'USER_MUST_RELOGIN' }
`

**Comment by ludwich** [comment]
hmmm user must relogin. That is weird. Will look at retry logic.

**Comment by ludwich** [comment]
Does postman work?

**Comment by reyntjensw** [comment]
In postman you get an empty list 
`{
    "data": [
        {
            "devId": 1000000035658220,
            "dataItemMap": {}
        }
    ],
    "failCode": 0,
    "message": null,
    "params": {
        "currentTime": 1673195771631,
        "devIds": "1000000035658220",
        "devTypeId": 39
    },
    "success": true
}`

**Comment by ludwich** [comment]
Then support have to step in.

**Comment by Mimomaj** [comment]
Thanks guys for spending time on this. I'll contact the support. I'll share with them the postman response right?

**Comment by ludwich** [comment]
Yes share the response and they should hopefully fix this.

**Comment by Mimomaj** [comment]
OK thanks!

**Comment by reyntjensw** [comment]
@Mimomaj  can I close this issue?
Was your problem solved?

**Comment by Mimomaj** [comment]
Hi @reyntjensw , could you please share with me the request that you did in postman? Huawei support can't follow up on this without that

**Comment by reyntjensw** [comment]
@Mimomaj can you create another diagnostics report please?

**Comment by Mimomaj** [comment]
@reyntjensw here it is 5d0c1f84-afa0-47a0-b559-55f89df1a486

**Comment by reyntjensw** [comment]
@Mimomaj here you go, the error we get is :
`---- stdout ----
[log] 2023-02-07 07:32:42 [HuaweiSolar] HuaweiSolar has been initialized
[log] 2023-02-07 07:32:43 [ManagerDrivers] [Driver:luna] Luna has been initialized
[log] 2023-02-07 07:32:43 [ManagerDrivers] [Driver:luna] [Device:e76721d3-18c1-48f3-8767-c3cc1aeb905d] Huawei has been initialized
server:  region02eu5
[log] 2023-02-07 07:32:44 [ManagerDrivers] [Driver:luna] [Device:e76721d3-18c1-48f3-8767-c3cc1aeb905d] get basic Data
[log] 2023-02-07 07:32:44 [ManagerDrivers] [Driver:luna] [Device:e76721d3-18c1-48f3-8767-c3cc1aeb905d] get current Data
[log] 2023-02-07 07:32:44 [ManagerDrivers] [Driver:luna] [Device:e76721d3-18c1-48f3-8767-c3cc1aeb905d] devListpowerMeterId {
  devName: 'Battery-1',
  devTypeId: 39,
  esnCode: null,
  id: 1000000035658220,
  invType: null,
  latitude: 48.224056,
  longitude: 17.242726,
  optimizerNumber: null,
  softwareVersion: null,
  stationCode: 'NE=35658216'
}
[log] 2023-02-07 07:32:45 [ManagerDrivers] [Driver:luna] [Device:e76721d3-18c1-48f3-8767-c3cc1aeb905d] devRealKpiBattery {}

---- stderr ----
[err] 2023-02-07 07:32:45 [ManagerDrivers] [Driver:luna] [Device:e76721d3-18c1-48f3-8767-c3cc1aeb905d] Unavailable (Error: measure_battery InvalidTypeError: undefined is undefined but expected number (invalid_type))`

When we look at the code, this is triggered at line https://github.com/reyntjensw/Homey-FusionSolar/blob/main/drivers/luna/device.js#L112

The api call that is being triggered here is https://github.com/reyntjensw/Homey-FusionSolar/blob/1c07ccf2e3f8fbf45778130609586e4d0c7209a1/drivers/luna/api.js#L137

**Comment by Mimomaj** [comment]
@reyntjensw So is that ok if I share all of this with the Huawei support?

**Comment by reyntjensw** [comment]
sure this is all public information :)

**Comment by krosso65** [comment]
Any News on This? I have the same problem

**Comment by krosso65** [comment]
fe3d8dd6-4072-456c-b8ab-56a55df97a67

**Comment by krosso65** [comment]
My diag

**Comment by reyntjensw** [comment]
@krosso65 what is the update from Huawei?

**Comment by krosso65** [comment]
I now got the right permissions. But still the device goes "unavailable" , but sometime when I look it works even if I do nothing for a short while?!?!  have you seen the same or is I alone with this?

**Comment by reyntjensw** [comment]
@krosso65 can you send me a diag report please?

**Comment by reyntjensw** [comment]
I don't see anything in the logs that could indicate a problem.
I have published a new test version, please try it out

**Comment by krosso65** [comment]
Ok, how to install test-version?

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Wouter Reyntjens ***@***.***>
Skickat: Wednesday, May 10, 2023 8:05:08 PM
Till: reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: krosso65 ***@***.***>; Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)


I don't see anything in the logs that could indicate a problem.
I have published a new test version, please try it out

**Comment by reyntjensw** [comment]
@krosso65 can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by krosso65** [comment]
Hello
When try to add a device with ”webb” I got invalid login, tried both web user and email
When try to add with ”before or after 2023” using api user I got error in screenshot

/regards Per

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Wouter Reyntjens ***@***.***>
Skickat: Sunday, May 21, 2023 12:07:36 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: krosso65 ***@***.***>; Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)


@krosso65<https://github.com/krosso65> can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by krosso65** [comment]
After your last update 2.0.5 it seems to work :)
Missing some values, see screenshot

/regards Per


Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Per Rosshagen ***@***.***>
Skickat: Sunday, May 21, 2023 10:15:19 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>; reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)

Hello
When try to add a device with ”webb” I got invalid login, tried both web user and email
When try to add with ”before or after 2023” using api user I got error in screenshot

/regards Per

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Wouter Reyntjens ***@***.***>
Skickat: Sunday, May 21, 2023 12:07:36 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: krosso65 ***@***.***>; Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)


@krosso65<https://github.com/krosso65> can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by reyntjensw** [comment]
Good morning, the screenshot did not come through.  If you have a battery, for now you need to restart the app, there is a known bug

Op 21 mei 2023 22:58 schreef krosso65 ***@***.***>:

After your last update 2.0.5 it seems to work :)
Missing some values, see screenshot

/regards Per


Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Per Rosshagen ***@***.***>
Skickat: Sunday, May 21, 2023 10:15:19 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>; reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)

Hello
When try to add a device with ”webb” I got invalid login, tried both web user and email
When try to add with ”before or after 2023” using api user I got error in screenshot

/regards Per

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Wouter Reyntjens ***@***.***>
Skickat: Sunday, May 21, 2023 12:07:36 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: krosso65 ***@***.***>; Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)


@krosso65<https://github.com/krosso65> can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by krosso65** [comment]
Hello

Thats worked 😊
How often does the values update?
My Daily yield is very slow (now 9h since last update)
Monthly yield is much faster

/Regards Per

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: Wouter ***@***.***>
Skickat: den 22 maj 2023 07:01
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)

Good morning, the screenshot did not come through. If you have a battery, for now you need to restart the app, there is a known bug

Op 21 mei 2023 22:58 schreef krosso65 ***@***.***>:

After your last update 2.0.5 it seems to work :)
Missing some values, see screenshot

/regards Per


Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Per Rosshagen ***@***.***>
Skickat: Sunday, May 21, 2023 10:15:19 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>; reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)

Hello
When try to add a device with ”webb” I got invalid login, tried both web user and email
When try to add with ”before or after 2023” using api user I got error in screenshot

/regards Per

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Wouter Reyntjens ***@***.***>
Skickat: Sunday, May 21, 2023 12:07:36 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: krosso65 ***@***.***>; Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)


@krosso65<https://github.com/krosso65> can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by reyntjensw** [comment]
Every 2 minutes an update is triggered

From: krosso65 ***@***.***>
Date: Monday, 22 May 2023 at 19:54
To: reyntjensw/Homey-FusionSolar ***@***.***>
Cc: Wouter Reyntjens ***@***.***>, Mention ***@***.***>
Subject: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)
Hello

Thats worked 😊
How often does the values update?
My Daily yield is very slow (now 9h since last update)
Monthly yield is much faster

/Regards Per

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: Wouter ***@***.***>
Skickat: den 22 maj 2023 07:01
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)

Good morning, the screenshot did not come through. If you have a battery, for now you need to restart the app, there is a known bug

Op 21 mei 2023 22:58 schreef krosso65 ***@***.***>:

After your last update 2.0.5 it seems to work :)
Missing some values, see screenshot

/regards Per


Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Per Rosshagen ***@***.***>
Skickat: Sunday, May 21, 2023 10:15:19 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>; reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)

Hello
When try to add a device with ”webb” I got invalid login, tried both web user and email
When try to add with ”before or after 2023” using api user I got error in screenshot

/regards Per

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Wouter Reyntjens ***@***.***>
Skickat: Sunday, May 21, 2023 12:07:36 AM
Till: reyntjensw/Homey-FusionSolar ***@***.***>
Kopia: krosso65 ***@***.***>; Mention ***@***.***>
Ämne: Re: [reyntjensw/Homey-FusionSolar] Device unavailable after ticking on battery in settings (Issue #18)


@krosso65<https://github.com/krosso65> can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw
