### ISSUE TITLE
Energy consumption

### ISSUE THREAD

**Issue by khandanpour** [reyntjensw/Homey-FusionSolar#79]
Hi Wouter, 
thanx for that great app. But is there any way to get information about energy usage in my house? The fusion solar app does show home energy consumption. Isn't possible to get that data from Huawei API?
Second question: There is a modbus TCP Integreation on the huawei Inveters. SO it must be possible to directly get that information from local network without request limitations. Do you know a way to get this data?

**Comment by reyntjensw** [comment]
@khandanpour thanks for your message.
I'm referring to this issue https://github.com/reyntjensw/Homey-FusionSolar/issues/76#issuecomment-1627663646

The issue is that Huawei has multiple integration of Modbus and all these kind of integrations will generate a lot of support tickets. If people have time to work out the modbus integration, I'm ok with integrating it but I will not create it.

I already tried it and it was not working.
